.TH TABBED 1 tabbed\-VERSION
.SH NAME
tabbed \- generic tabbed interface
.SH SYNOPSIS
.B tabbed
.RB [ \-d ]
.RB [ \-h ]
.RB [ \-s ]
.RB [ \-v ]
.RB [ \-n
.IR name ]
.RB [ \-r
.IR narg ]
.IR [ command ... ]
.SH DESCRIPTION
.B tabbed
is a simple tabbed container for applications which support XEmbed. Tabbed
will then run the provides command with the xid of tabbed as appended
argument. (See EXAMPLES.) The automatic spawning of the command can be
disabled by providing the -s parameter. If no command is provided
tabbed will just print its xid and run no command.
.SH OPTIONS
.TP
.B \-d
detaches tabbed from the terminal and prints its XID to stdout.
.TP
.B \-h
will print the usage of tabbed.
.TP
.BI \-n " name"
will set the WM_CLASS attribute to
.I name.
.TP
.BI \-r " narg"
will replace the
.I narg
th argument in
.I command
with the window id, rather than appending it to the end.
.TP
.B \-s
will disable automatic spawning of the command.
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.TP
.B Ctrl\-Shift\-Return
open new tab
.TP
.B Ctrl\-Shift\-h
previous tab
.TP
.B Ctrl\-Shift\-l
next tab
.TP
.B Ctrl\-Tab
toggle between tabs
.TP
.B Ctrl\-q
close tab
.TP
.B Ctrl\-[0..9]
jumps to nth tab
.SH EXAMPLES
$ tabbed surf -e
.TP
$ tabbed urxvt -embed
.TP
$ tabbed xterm -into
.TP
$ $(tabbed -d >/tmp/tabbed.xid); urxvt -embed $(</tmp/tabbed.xid);
.TP
$ tabbed -r 2 st -w '' -e tmux
.SH CUSTOMIZATION
.B tabbed
can be customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR st (1)
.SH BUGS
Please report them.

