.TH TABBED 1 tabbed\-VERSION
.SH NAME
tabbed \- simple generic tabbed interface
.SH SYNOPSIS
.B tabbed
.RB [ \-dhv ]
.RB "URI"
.SH DESCRIPTION
tabbed is a simple container for applications which support XEmbed, such as
xterm or surf.
.SH OPTIONS
.TP
.B \-d
detaches tabbed from the terminal. Usefull for scripting.
.TP
.B \-h
Prints usage information to standard output, then exits.
.TP
.B \-v
Prints version information to standard output, then exits.
.SH USAGE
.TP
.B Ctrl\-Shift\-Return
new surf-window.
.TP
.B Ctrl\-Shift\-h
previous tab
.TP
.B Ctrl\-Shift\-l
next tab
.TP
.B Ctrl\-q
closes the tab
.TP
.B Ctrl\-[0-9]
jumps to n-th tab
.SH SEE ALSO
.BR xterm(1)
.BR surf(1)
.SH BUGS
Please report them!
